### PR TITLE
Drop long-running linux-aarch64 builds

### PR DESCRIPTION
**Pull request by jdblischak**
I fixed the linux-aarch64 builds in #44. However, they take forever to build (4-6 hours), and thus they delay our updates, eg #45.

We now have a few conda binaries available for linux-aarch64. That should be sufficient for anyone curious to test tiledb-vector-search on that platform. But until a user explicitly requests linux-aarch64, I don't think we should drop these builds.

### CODE REVIEW

**Review by teo-tsirpanis — COMMENTED** [review]
Any idea why do they take so long? Is it something intermittent or a problem in the vector search codebase?

**Review by dudoslav — APPROVED** [review]
Do we actually have any users that use linux aarch64?

**Comment by jdblischak** [comment]
> Any idea why do they take so long? Is it something intermittent or a problem in the vector search codebase?

No idea. I was hoping it was transient last night, but once again today it is unbearably slow. Our other builds take longer on linux-aarch64 compared to linux-64, but nowhere close to this long.

**Comment by jdblischak** [comment]
> Do we actually have any users that use linux aarch64?

No, at least not any users of tiledb-vector-search. Prior to last night, no linux-aarch64 conda binaries even existed

**Comment by johnkerl** [comment]
> Do we actually have any users that use linux aarch64?

It is a "new thing" which some people are beginning to ask for. There are linux-aarch64 instances with a very nice price/performance ratio.

**Comment by ihnorton** [comment]
Looking at the log, solver step takes ~15', but build is comically slow -- that's where the hours go, chugging through cpp files. The runner is x86_64 so the conda build must be running under emulation.

**Comment by teo-tsirpanis** [comment]
I think it does cross-compiling but I am not 100% sure.

**Comment by jdblischak** [comment]
It runs the test section, so I don't think it is cross-compiled

**Pull request merged**
