### PR TITLE
Release Vector Search 0.6.0

### PR DESCRIPTION
**Pull request by jparismorgan**
### What
Release [Vector Search 0.6.0](https://github.com/TileDB-Inc/TileDB-Vector-Search/releases/tag/0.6.0). Based on:
* https://github.com/TileDB-Inc/TileDB-Vector-Search/actions/runs/9760058248
* https://pypi.org/project/tiledb-vector-search/0.6.0/#copy-hash-modal-15dce4e5-4793-4dde-acba-14853ab516ab

### CODE REVIEW

**Review by teo-tsirpanis — APPROVED** [review]

**Comment by jparismorgan** [comment]
Actually, I missed updating Core here, updating now, one minute please.

**Review by dudoslav — APPROVED** [review]
Thanks for adding the comment, LGTM

**Comment by jparismorgan** [comment]
Okay so I unintentionally did not change the `- tiledb >=2.24,<2.25` line (https://github.com/TileDB-Inc/tiledb-vector-search-feedstock/blob/main/recipe/meta.yaml#L42), but I believe it's actually correct, as we're now on `2.24.1` for https://anaconda.org/conda-forge/tiledb, which is included in this.

Does that seem correct to you all? Or do you know if I have to update to `- tiledb >=2.24.1,<2.25`?

**Comment by johnkerl** [comment]
> Does that seem correct to you all? Or do you know if I have to update to - tiledb >=2.24.1,<2.25?

Please do that: 2.25 doesn't exist _yet_ but it will real soon now.

**Comment by jparismorgan** [comment]
Mmm maybe I'm misunderstanding something, but I don't believe that this change will affect `2.25`. It's just about whether we want to do:
a. `- tiledb >=2.24,<2.25`
b. `- tiledb >=2.24.1,<2.25`

**Comment by johnkerl** [comment]
@jparismorgan ah ok thanks then!

**Comment by dudoslav** [comment]
@jparismorgan I can see that in our previous PRs we only bumped up tiledb dependency when the minor version changed. So in this case we would keep it as is. So keep a. I guess?

**Comment by jdblischak** [comment]
> Does that seem correct to you all? Or do we have to update to `- tiledb >=2.24.1,<2.25` so that `2.24.0` is no longer valid?

@jparismorgan This depends. 0.6.0 has been updated to bundle libtiledb 2.24.1 in its wheel build. But this isn't the same thing as actually requiring >=2.24.1. Did any code in tiledb-vector-search change that would cause it to fail if it was run with 2.24.0? If no, then there is no reason to bump the pin.

**Comment by jdblischak** [comment]
FYI just yesterday I fixed the linux-aarch64 builds in #44. Unfortunately, for some strange reason, these builds took 4-6 hours to complete. Maybe today it will be better. But if not, I think we should drop the linux-aarch64 builds until they are explicitly requested by a user.

**Review by jdblischak — APPROVED** [review]

**Comment by jparismorgan** [comment]
> Did any code in tiledb-vector-search change that would cause it to fail if it was run with 2.24.0? If no, then there is no reason to bump the pin.

No, nothing changed. Okay sounds good, I will leave it at `- tiledb >=2.24,<2.25`.

**Comment by jdblischak** [comment]
The linux-aarch64 builds are not going to complete for hours. There is nothing in this PR that suggests they will not succeed post-merge.

I propose we either:

1) Drop the linux-aarch64 builds
2) Merge now instead of waiting for them to complete

**Comment by jparismorgan** [comment]
Hi sorry I'm offline for the next three hours! Either plan is fine with me. If we're blocked please feel free to merge, else I'll disable them and run again when I'm back online.

**Pull request merged**
