### PR TITLE
Release 0.8.1

### PR DESCRIPTION
**Pull request by NikolaosPapailiou**

### CODE REVIEW

**Review by dudoslav — APPROVED** [review]

**Review by jparismorgan — APPROVED** [review]

**Review by jdblischak — APPROVED** [review]

**Comment by jdblischak** [comment]
I don't think this is the problem, but just wanted to give the heads up that it looks like the image version isn't stable.

* The [py310 build](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=40720&view=logs&jobId=ce4c1b9d-afa5-5397-2c0a-4b68424429b0&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=e9be3436-5f0c-4307-b8c4-78a7d7aeff6e) passed with 20240908.1.0
* The [py39 build](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=40720&view=logs&jobId=ce4c1b9d-afa5-5397-2c0a-4b68424429b0&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=4eab1651-eec1-4e38-8bd5-ecc54b5b39a4&s=96ac2280-8cb4-5df5-99de-dd2da759617d) failed with 20240901.1.0
* The [py311 build](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=40720&view=logs&jobId=ce4c1b9d-afa5-5397-2c0a-4b68424429b0&j=517fe804-fa30-5dc2-1413-330699242c05&t=936a5489-61db-4da1-a995-9a519a8ce181) passed with 20240901.1.0
* The restarted py39 builds continue to fail with 20240901.1.0

Looking at the docs PR for Ubuntu 22.04 20240908 https://github.com/actions/runner-images/pull/10574, the only relevant change I see is that Vcpkg was updated

**Comment by teo-tsirpanis** [comment]
Vector search does not use vcpkg (yet).

**Comment by NikolaosPapailiou** [comment]
I think this is related to a bug in pybind11 https://github.com/pybind/pybind11/issues/5224

**Comment by dudoslav** [comment]
Depending if we want to only add it to this feedstock, then I would suggest appending `CXX_FLAGS` and `CC_FLAGS` with these options. I am not sure about a best way to do it in meta.yaml, perhaps @jdblischak knows?

Otherwise if we want to have this in every build, even pypi builds we need to add it to CMakeLists as `target_compile_options` to the correct target. I am not sure if this is needed though. I can see that pypi wheels were produced correctly.

**Comment by NikolaosPapailiou** [comment]
This still fails both after passing the extra compiler flags and switching to GCC 13. 

With GCC 13, I don't see the `pybind` warning, so this was not the problem. 

From the logs, it seems that the worker dies unexpectedly during `[ 99%] Building CXX object python/CMakeFiles/_tiledbvspy.dir/src/tiledb/vector_search/type_erased_module.cc.o`

**Comment by NikolaosPapailiou** [comment]
> I don't think this is the problem, but just wanted to give the heads up that it looks like the image version isn't stable.
> 
> * The [py310 build](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=40720&view=logs&jobId=ce4c1b9d-afa5-5397-2c0a-4b68424429b0&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=e9be3436-5f0c-4307-b8c4-78a7d7aeff6e) passed with 20240908.1.0
> * The [py39 build](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=40720&view=logs&jobId=ce4c1b9d-afa5-5397-2c0a-4b68424429b0&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=4eab1651-eec1-4e38-8bd5-ecc54b5b39a4&s=96ac2280-8cb4-5df5-99de-dd2da759617d) failed with 20240901.1.0
> * The [py311 build](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=40720&view=logs&jobId=ce4c1b9d-afa5-5397-2c0a-4b68424429b0&j=517fe804-fa30-5dc2-1413-330699242c05&t=936a5489-61db-4da1-a995-9a519a8ce181) passed with 20240901.1.0
> * The restarted py39 builds continue to fail with 20240901.1.0
> 
> Looking at the docs PR for Ubuntu 22.04 20240908 [actions/runner-images#10574](https://github.com/actions/runner-images/pull/10574), the only relevant change I see is that Vcpkg was updated

@jdblischak do you know if we can select another image for the py39 build?

**Comment by jdblischak** [comment]
> Also could this be related to the docker image https://quay.io/repository/condaforge/linux-anvil-cos7-x86_64 we are using? This was updated 9 days ago

That update from 9 days ago was from this PR https://github.com/conda-forge/docker-images/pull/276

I don't see why that PR would cause only our py39 build to fail but not the others. The CUDA version was upgraded, but I don't think we are even using the CUDA-enabled images, so this should have no effect.

**Comment by jdblischak** [comment]
I remembered the difference between the py39 build and the py310/py311 builds! The py39 build includes all the debug info (since it is deployed to TileDB Cloud), but py310/py311 are release builds (https://github.com/TileDB-Inc/tiledb-vector-search-feedstock/pull/50)

**Comment by NikolaosPapailiou** [comment]
> I remembered the difference between the py39 build and the py310/py311 builds! The py39 build includes all the debug info (since it is deployed to TileDB Cloud), but py310/py311 are release builds (#50)

Thanks @jdblischak! Generating the debug symbols was what caused the problem. I will disable this for now and we will follow up in [sc-55001](https://app.shortcut.com/tiledb-inc/story/55001/vectror-search-release-0-8-1-caused-azure-worker-errors-while-compiling-with-debug-symbols) to try to re-enable the debug symbols build.

**Pull request merged**
